/**
 * Fixture feed: replays web/public/fixtures/mock.jsonl (generated by
 * scripts/gen-fixture.mjs) through the same `ingest` path as the WebSocket.
 *
 * Pacing: the first `VITE_FIXTURE_BURST` ticks (default 40) are delivered at
 * once, like the server's ≤ 60-snapshot ring replay on connect. After that each
 * tick is delivered after a delay derived from the fixture's own ts_ms deltas,
 * scaled by `VITE_FIXTURE_PACE` (default 0.6 → ~1.7× real time) and jittered
 * ±30 % by a seeded PRNG so arrival intervals are irregular and the history
 * buffer's EMA clamp is exercised. ts_ms is rescaled by the same factor so the
 * virtual timeline stays consistent with wall time; the 20 s pause gap in the
 * fixture survives as a (pace-scaled) gap that the clamp absorbs.
 */
import type { ServerMsg, SnapshotMsg } from '../protocol'
import { useStore } from '../state/store'
import { ingest, isServerMsg } from './ingest'

function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function envNumber(name: string, fallback: number): number {
  const raw = (import.meta.env as Record<string, string | undefined>)[name]
  const v = raw === undefined ? NaN : Number(raw)
  return Number.isFinite(v) ? v : fallback
}

export async function startFixture(): Promise<() => void> {
  const store = useStore.getState()
  store.setConn('connecting', 'fixture')
  const res = await fetch('/fixtures/mock.jsonl')
  if (!res.ok) {
    console.error('fixture missing: run `npm run gen:fixture`')
    store.setConn('closed', 'fixture')
    return () => {}
  }
  const text = await res.text()
  const msgs: ServerMsg[] = []
  for (const line of text.split('\n')) {
    const t = line.trim()
    if (!t) continue
    try {
      const m: unknown = JSON.parse(t)
      if (isServerMsg(m)) msgs.push(m)
    } catch {
      /* skip malformed line */
    }
  }

  const pace = Math.max(0.05, envNumber('VITE_FIXTURE_PACE', 0.6))
  const burst = Math.max(0, Math.floor(envNumber('VITE_FIXTURE_BURST', 40)))
  const maxDelay = envNumber('VITE_FIXTURE_MAX_DELAY_MS', 4000)
  const rand = mulberry32(20260930)

  // Rescale ts_ms so virtual time advances at wall-clock speed under `pace`.
  const firstSnap = msgs.find((m): m is SnapshotMsg => m.type === 'snapshot')
  const ts0 = firstSnap ? firstSnap.ts_ms : 0
  const scaled = msgs.map((m) => (m.type === 'snapshot' ? { ...m, ts_ms: Math.round(ts0 + (m.ts_ms - ts0) * pace) } : m))
  const scaledHello = scaled.map((m) => (m.type === 'hello' ? { ...m, server_ts_ms: Math.round(ts0 + (m.server_ts_ms - ts0) * pace) } : m))

  let cancelled = false
  let timer: ReturnType<typeof setTimeout> | null = null
  let i = 0
  let snapsDelivered = 0
  let lastTs = ts0

  const deliverUntilNextSnapshot = (): SnapshotMsg | null => {
    // Deliver messages up to and including the next snapshot.
    while (i < scaledHello.length) {
      const m = scaledHello[i++]!
      ingest(m)
      if (m.type === 'snapshot') {
        snapsDelivered++
        lastTs = m.ts_ms
        return m
      }
    }
    return null
  }

  const drainTail = (): void => {
    // Messages after the final snapshot (day rows, chronicle) go out immediately.
    while (i < scaledHello.length) ingest(scaledHello[i++]!)
  }

  const schedule = (): void => {
    if (cancelled) return
    // Peek the next snapshot's ts to derive the real delay before delivering its group.
    let j = i
    let next: SnapshotMsg | null = null
    while (j < scaledHello.length) {
      const m = scaledHello[j++]!
      if (m.type === 'snapshot') {
        next = m
        break
      }
    }
    if (!next) {
      drainTail()
      store.setConn('fixture', 'fixture')
      return
    }
    const dt = Math.max(60, next.ts_ms - lastTs)
    const jitter = 0.7 + rand() * 0.6
    const delay = Math.min(maxDelay, dt * jitter)
    timer = setTimeout(() => {
      timer = null
      deliverUntilNextSnapshot()
      schedule()
    }, delay)
  }

  // Connect burst: preamble + first `burst` ticks at once.
  while (snapsDelivered < burst && i < scaledHello.length) {
    if (!deliverUntilNextSnapshot()) break
  }
  store.setConn('fixture', 'fixture')
  schedule()

  return () => {
    cancelled = true
    if (timer) clearTimeout(timer)
    timer = null
  }
}
